# Generated by Django 6.0.2 on 2026-02-12 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image_in_detail_1',
            field=models.ImageField(blank=True, default='product3.png', upload_to='image_product/', verbose_name='Image in detail 1'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_in_detail_2',
            field=models.ImageField(blank=True, default='product3.png', upload_to='image_product/', verbose_name='Image in detail 2'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_in_detail_3',
            field=models.ImageField(blank=True, default='product3.png', upload_to='image_product/', verbose_name='Image in detail 3'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_product',
            field=models.ImageField(blank=True, default='product3.png', upload_to='image_product/', verbose_name='Image'),
        ),
    ]
