# Generated by Django 6.0.2 on 2026-02-12 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_product_image_in_detail_1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='phone',
        ),
        migrations.AlterField(
            model_name='person',
            name='email',
            field=models.CharField(blank=True, max_length=127, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_in_detail_1',
            field=models.ImageField(blank=True, default='product3.jpg', upload_to='image_product/', verbose_name='Image in detail 1'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_in_detail_2',
            field=models.ImageField(blank=True, default='product3.jpg', upload_to='image_product/', verbose_name='Image in detail 2'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_in_detail_3',
            field=models.ImageField(blank=True, default='product3.jpg', upload_to='image_product/', verbose_name='Image in detail 3'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_product',
            field=models.ImageField(blank=True, default='product3.jpg', upload_to='image_product/', verbose_name='Image'),
        ),
    ]
